### ISSUE TITLE
Problem mit der Ratte

### ISSUE THREAD

**Issue by luap-r** [ja26gu/ultimate-js-experiments#1]
Bei testen des Spiel der Ratte stand ich mit der zahl 4 immer als looser da, obwohl es angezeigt hat, das es richtig war eigentlich. Ich hoffe das wird gefixt.

Mit freundlichen Grüßen 
Ja26nö

**Comment by ja26gu** [comment]
so hab gefixt

**Comment by luap-r** [comment]
Danke
